[package]
name = "tokenizers_net"
version = "1.0.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "lib"]

[build-dependencies]
csbindgen = "1.9.3"

[dependencies]
tokenizers = "0.20.0"

# sssss
