# https://medium.com/@m.b1lal/how-to-use-github-actions-to-run-nunit-tests-and-publish-allure-reports-to-github-pages-224866d3ea2e

name: NUnit Tests and Deploy Allure Reports

on:
  push:
    branches:
      - main

jobs:
  wait-for-workflows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}

      - name: Wait for workflows
        id: wait
        uses: budgetdevv/chainlink-github-actions/utils/wait-for-workflows@main
        with:
          max-timeout: "900"
          polling-interval: "30"
          exclude-workflow-names: ""
          exclude-workflow-ids: ""
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEBUG: "true"
          
  test:
    runs-on: macos-latest
    needs: [wait-for-workflows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --framework net8.0 --no-restore /p:SetupGHTestWorkflow=true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4.0.0
        with:
          name: allure-results
          path: Tests/bin/Debug/net8.0/allure-results
          if-no-files-found: error
          retention-days: 20

  generate-report:
    name: Generate and Deploy Allure Report to Github Pages
    needs: test
    
    # "Container action is only supported on Linux"
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        # uses: peaceiris/actions-github-pages@v3.1.12
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report
          
          
  publish-nuget:
    needs: test

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Get short commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set Alpha Version
        run: |
          ALPHA_VERSION=alpha-${COMMIT_SHA}
          echo "ALPHA_VERSION=$ALPHA_VERSION" >> $GITHUB_ENV
          
      - name: Restore dependencies
        working-directory: Tokenizers.NET
        run: dotnet restore
          
      - name: Build NuGet package
        working-directory: Tokenizers.NET
        run: dotnet pack -c Release -v:m /p:AlphaVersion=${ALPHA_VERSION} /p:DownloadNativeFiles=true
      
      - name: Publish NuGet package
        working-directory: Tokenizers.NET
        run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate bin/Release/*.nupkg
     
