# https://medium.com/@m.b1lal/how-to-use-github-actions-to-run-nunit-tests-and-publish-allure-reports-to-github-pages-224866d3ea2e

name: Test, Publish NuGet and Generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  wait-for-workflows:
    name: Wait for other workflows to complete
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}

      - name: Wait for workflows
        id: wait
        uses: budgetdevv/chainlink-github-actions/utils/wait-for-workflows@main
        with:
          max-timeout: "900"
          polling-interval: "30"
          exclude-workflow-names: ""
          exclude-workflow-ids: ""
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEBUG: "true"
          
  test-and-publish:
    name: Test and Publish NuGet
    runs-on: macos-latest
    needs: [wait-for-workflows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --framework net8.0 --no-restore /p:SetupGHTestWorkflow=true
        
      - name: Get short commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # https://stackoverflow.com/questions/77882485/github-actions-resource-not-accessible-by-integration 
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get and increment alpha version number
        id: bump_version
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          CURRENT_ALPHA_VERSION_NUMBER=$(gh variable get ALPHA_VERSION_NUMBER)
          NEW_ALPHA_VERSION_NUMBER=$((CURRENT_ALPHA_VERSION_NUMBER + 1))
          echo "NEW_ALPHA_VERSION_NUMBER=$NEW_ALPHA_VERSION_NUMBER" >> $GITHUB_OUTPUT

      - name: Update ALPHA_VERSION_NUMBER in repository variable
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh variable set ALPHA_VERSION_NUMBER -b "${{ steps.bump_version.outputs.NEW_ALPHA_VERSION_NUMBER }}"

      - name: Set Alpha Version
        id: set_version
        run: |
          ALPHA_VERSION=alpha-${{ steps.bump_version.outputs.NEW_ALPHA_VERSION_NUMBER }}-${{ steps.vars.outputs.COMMIT_SHA }}
          echo "ALPHA_VERSION=$ALPHA_VERSION" >> $GITHUB_OUTPUT

      - name: Build NuGet package
        working-directory: Tokenizers.NET
        run: dotnet pack -c Release -v:m --no-restore /p:DownloadNativeFiles=true /p:AlphaVersion=${{ steps.set_version.outputs.ALPHA_VERSION }}

      - name: Publish NuGet package
        working-directory: Tokenizers.NET
        run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate bin/Release/*.nupkg
        
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4.0.0
        with:
          name: allure-results
          path: Tests/bin/Debug/net8.0/allure-results
          if-no-files-found: error
          retention-days: 20

  generate-report:
    name: Generate and Deploy Allure Report to Github Pages
    needs: test-and-publish
    
    # "Container action is only supported on Linux"
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: allure-results
          path: ./allure-results

      - name: Generate report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        # uses: peaceiris/actions-github-pages@v3.1.12
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report


     
